nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin:
            - '^http://localhost:8081$'
            - '^http://127\.0\.0\.1:8081$'
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-User-Id']
        max_age: 3600

    paths:
        '^/':
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - '^http://localhost:8081$'
                - '^http://127\.0\.0\.1:8081$'
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-User-Id']
            max_age: 3600