nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '^https://ymeal-front\.osc-fr1\.scalingo\.io$'
            - '^http://localhost.*$'
        allow_headers: ['Content-Type', 'X-CSRF-TOKEN', 'Authorization', 'X-User-Id']
        allow_methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/':
            origin_regex: true
            allow_origin:
                - '^https://ymeal-front\.osc-fr1\.scalingo\.io$'
                - '^http://localhost.*$'
            allow_headers: ['Content-Type', 'X-CSRF-TOKEN', 'Authorization', 'X-User-Id']
            allow_methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600